library(RCurl)
library(XML)
html <- getURL("https://en.wikipedia.org/wiki/ISO_3166-2:VN", .encoding = "UTF-8", .mapUnicode = TRUE)
province.codes <- as.data.frame(readHTMLTable(html , which = 1)) 
names(province.codes) = c("code", "name", "cat")
province.codes$name = gsub("^.*!", "", province.codes$name)
